// Bundles the Supabase edge function (edge/submit-daily.ts + the game simulation) into a single file that Deno runs:
// supabase/functions/submit-daily/index.ts. Deploy with `supabase functions deploy submit-daily --no-verify-jwt`
// (see .github/workflows/supabase-edge.yml) or paste it in Supabase → Edge Functions → Deploy via editor.
// usage: node scripts/build-edge.mjs
import { build } from 'esbuild';
import { readFileSync, mkdirSync } from 'node:fs';
import { resolve } from 'node:path';

const version = /VERSION = '([^']+)'/.exec(readFileSync('src/config.ts', 'utf8'))?.[1] ?? '0';
mkdirSync('supabase/functions/submit-daily', { recursive: true });
await build({
  entryPoints: ['edge/submit-daily.ts'],
  bundle: true,
  format: 'esm',
  platform: 'neutral',
  target: 'es2022',
  outfile: 'supabase/functions/submit-daily/index.ts',
  external: ['jsr:*', 'npm:*', 'https://*'],
  define: { __GAME_VERSION__: JSON.stringify(version) },
  plugins: [{
    // the simulation data imports the translation layer; the server needs none of it
    name: 'i18n-stub',
    setup(b) { b.onResolve({ filter: /[\\/]i18n$/ }, () => ({ path: resolve('edge/i18n-stub.ts') })); },
  }],
  banner: { js: `// @ts-nocheck\n// GENERATED by scripts/build-edge.mjs from edge/submit-daily.ts — do not edit. Game version ${version}.` },
  legalComments: 'none',
  minify: false,
  treeShaking: true,
  logLevel: 'info',
});
console.log('edge function bundled for version', version);
